#!/bin/bash

#Use read to prompt the user for a name
read -p "Please enter your first and last name1: " firstlast

#Pass the user input to an echo statement
echo "Hello, $firstlast. Thank you for your input!"

